const S={snapshot:null,rank:null};const $=id=>document.getElementById(id);const num=(v,d=1)=>typeof v==='number'&&Number.isFinite(v)?v.toFixed(d):'—';const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function tileId(f){const p=f?.properties||{};for(const k of ['tile_id','tileId','id','tile','grid_id'])if(p[k]!=null&&!Number.isNaN(Number(p[k])))return Number(p[k]);return null}
function temp(f){const p=f?.properties||{};for(const k of ['average_temperature','avg_temperature','average','avg','temperature','tcm','mean_temperature','mean'])if(typeof p[k]==='number')return p[k];for(const [k,v] of Object.entries(p))if(typeof v==='number'&&/temp|average|mean|tcm/i.test(k))return v;return null}
function rings(g){if(!g)return[];if(g.type==='Polygon')return g.coordinates||[];if(g.type==='MultiPolygon')return(g.coordinates||[]).flat();return[]}
function points(features){const out=[];for(const f of features)for(const r of rings(f.geometry))for(const p of r||[])if(Array.isArray(p)&&p.length>=2&&Number.isFinite(+p[0])&&Number.isFinite(+p[1]))out.push([+p[0],+p[1]]);return out}
function center(f){const pts=points([f]);if(!pts.length)return null;return[pts.reduce((a,p)=>a+p[0],0)/pts.length,pts.reduce((a,p)=>a+p[1],0)/pts.length]}
function color(v,min,max){if(!Number.isFinite(v)||max===min)return'hsl(174 38% 36%)';const t=Math.max(0,Math.min(1,(v-min)/(max-min)));return`hsl(${205-t*195} 72% ${38+t*12}%)`}
function drawMap(){const svg=$('heatmapSvg'),features=S.snapshot?.heatmap_geojson?.features||[];svg.innerHTML='';if(!features.length){$('mapEmpty').classList.remove('hidden');return}$('mapEmpty').classList.add('hidden');const pts=points(features);if(!pts.length)return;const xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),pad=24,w=900,h=520,proj=p=>[pad+(p[0]-minX)/Math.max(maxX-minX,1e-9)*(w-2*pad),h-pad-(p[1]-minY)/Math.max(maxY-minY,1e-9)*(h-2*pad)],ts=features.map(temp).filter(Number.isFinite),tmin=Math.min(...ts),tmax=Math.max(...ts);
for(const f of features){const id=tileId(f),t=temp(f);for(const r of rings(f.geometry)){if(!r?.length)continue;const poly=document.createElementNS('http://www.w3.org/2000/svg','polygon');poly.setAttribute('points',r.map(p=>proj(p).join(',')).join(' '));poly.setAttribute('fill',color(t,tmin,tmax));poly.setAttribute('class','tile');poly.onmousemove=e=>{const tip=$('mapTooltip');tip.textContent=`Tile ${id??'—'}${Number.isFinite(t)?` • ${t.toFixed(2)} °C`:''}`;tip.style.left=`${e.offsetX+12}px`;tip.style.top=`${e.offsetY+12}px`;tip.classList.remove('hidden')};poly.onmouseleave=()=>$('mapTooltip').classList.add('hidden');svg.appendChild(poly)}}
for(const hs of S.snapshot.hotspots){const f=features.find(x=>tileId(x)===Number(hs.tile_id)),c=f?center(f):null;if(!c)continue;const [cx,cy]=proj(c),g=document.createElementNS('http://www.w3.org/2000/svg','g'),circle=document.createElementNS('http://www.w3.org/2000/svg','circle'),text=document.createElementNS('http://www.w3.org/2000/svg','text');g.onclick=()=>select(hs.hotspot_rank);circle.setAttribute('cx',cx);circle.setAttribute('cy',cy);circle.setAttribute('r',hs.hotspot_rank===S.rank?'14':'11');circle.setAttribute('class','marker');text.setAttribute('x',cx);text.setAttribute('y',cy+4);text.setAttribute('text-anchor','middle');text.setAttribute('class','marker-label');text.textContent=hs.hotspot_rank;g.append(circle,text);svg.appendChild(g)}}
function kpis(){const s=S.snapshot.summary;$('kpiHotspots').textContent=s.hotspot_count??'—';$('kpiPriority').textContent=num(s.highest_priority_score,2);$('kpiPriorityRank').textContent=s.highest_priority_rank?`Hotspot rank ${s.highest_priority_rank}`:'Verified planning order';$('kpiTemp').textContent=typeof s.max_historical_air_temperature_celsius==='number'?`${s.max_historical_air_temperature_celsius.toFixed(2)} °C`:'—';$('kpiTiles').textContent=s.heatmap_feature_count??0}
function ranking(){const el=$('rankingList');el.innerHTML='';S.snapshot.hotspots.forEach((h,i)=>{const d=document.createElement('div');d.className=`rank${h.hotspot_rank===S.rank?' active':''}`;d.innerHTML=`<div class="rank-top"><span>#${i+1} PRIORITY</span><strong>${num(h.planning_priority,2)}</strong></div><h4>Hotspot rank ${h.hotspot_rank} • tile ${h.tile_id??'—'}</h4><div class="rank-meta"><span>${num(h.metrics.historical_air_temperature_celsius,2)} °C historical air</span><span>${esc(h.planning_priority_band||'planning priority')}</span></div><div class="bar"><i style="width:${Math.max(0,Math.min(100,h.planning_priority||0))}%"></i></div>`;d.onclick=()=>select(h.hotspot_rank);el.appendChild(d)})}
function details(){const h=S.snapshot.hotspots.find(x=>x.hotspot_rank===S.rank);if(!h)return;const m=h.metrics;$('detailTitle').textContent=`Hotspot rank ${h.hotspot_rank} • tile ${h.tile_id??'—'}`;$('detailBand').textContent=h.planning_priority_band||'planning priority';$('priorityScore').textContent=num(h.planning_priority,2);const deg=Math.max(0,Math.min(360,(h.planning_priority||0)*3.6));$('scoreRing').style.background=`conic-gradient(var(--accent) ${deg}deg,rgba(255,255,255,.06) ${deg}deg)`;const c=Object.fromEntries((h.contributions||[]).filter(x=>x?.component).map(x=>[x.component,x]));$('priorityExplanation').textContent=`Verified decomposition: hazard ${num(c.hazard?.weighted_points,2)} pts, mapped-exposure ${num(c.mapped_exposure?.weighted_points,2)} pts, context-sensitivity ${num(c.context_sensitivity_proxy?.weighted_points,2)} pts.`;
const metrics=[['Historical air temperature',`${num(m.historical_air_temperature_celsius,2)} °C`],['Historical heat index',`${num(m.historical_heat_index_celsius,1)} °C`],['Apparent temperature',`${num(m.historical_apparent_temperature_celsius,1)} °C`],['Wet-bulb temperature',`${num(m.historical_wet_bulb_temperature_celsius,1)} °C`],['Relative humidity',`${num(m.historical_relative_humidity_percent,1)}%`],['Mapped exposure proxy',num(m.mapped_exposure_proxy,2)]];$('metricGrid').innerHTML=metrics.map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');for(const [id,v] of [['vulnStatus',h.evidence_status.verified_operational_vulnerability],['capacityStatus',h.evidence_status.verified_adaptive_capacity],['medicalStatus',h.evidence_status.medical_risk_probability]]){const e=$(id);e.textContent=String(v||'unknown').toUpperCase();e.className=v==='withheld'?'withheld':'unknown'}$('actionList').innerHTML=(h.recommendations||[]).slice(0,5).map(a=>`<div class="action"><div class="row"><div><span class="tier">${esc(a.priority_tier||'CONTROLLED')}</span><h4>${esc(a.title||'Controlled action')}</h4></div><em>${esc(a.status||'guarded')}</em></div><p>${esc(a.recommendation||'')}</p></div>`).join('')}
function select(rank){S.rank=rank;ranking();details();drawMap()}
function message(role,text){const d=document.createElement('div');d.className=`msg ${role}`;d.innerHTML=`<small>${role==='user'?'YOU':'HEATSHIELD'}</small><p>${esc(text)}</p>`;$('chatWindow').appendChild(d);$('chatWindow').scrollTop=$('chatWindow').scrollHeight}
async function ask(q){const b=$('sendButton');b.disabled=true;b.textContent='Grounding…';message('user',q);try{const r=await fetch('/api/v1/copilot/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:q,mode:'auto',hotspot_rank:S.rank})}),p=await r.json();if(!r.ok)throw new Error(p.detail||`HTTP ${r.status}`);message('ai',p.answer||'No grounded answer returned.')}catch(e){message('ai',`Copilot unavailable: ${e.message}. Deterministic dashboard evidence remains available.`)}finally{b.disabled=false;b.textContent='Ask Copilot'}}
async function status(){try{const r=await fetch('/api/v1/copilot/status'),p=await r.json();$('copilotStatus').textContent=p.default_provider==='ollama'?'Local Qwen Ready':`${p.default_provider||'Copilot'} Ready`;$('copilotModel').textContent=p.model||(p.default_provider==='ollama'?'Qwen3 1.7B Local':'Grounded Copilot')}catch{$('copilotStatus').textContent='Copilot status unavailable'}}
async function init(){try{const r=await fetch('/api/v1/dashboard/overview'),p=await r.json();if(!r.ok)throw new Error(p.detail||`HTTP ${r.status}`);S.snapshot=p;S.rank=p.planning_order?.[0]??p.hotspots?.[0]?.hotspot_rank??null;$('scopeText').textContent=p.scenario.scope_warning||p.scenario.statement||'Verified scenario replay';const hash=p.provenance?.day7_artifact_sha256;$('provenanceHash').textContent=hash?`Evidence SHA ${hash.slice(0,12)}…`:'Evidence lineage available';kpis();ranking();details();drawMap()}catch(e){$('scopeText').textContent=`Dashboard evidence could not be loaded: ${e.message}`;$('mapEmpty').classList.remove('hidden')}status()}
$('copilotForm').onsubmit=e=>{e.preventDefault();const i=$('copilotInput'),q=i.value.trim();if(!q)return;i.value='';ask(q)};document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>ask(S.rank?b.dataset.prompt.replace(/hotspot \d+/i,`hotspot ${S.rank}`):b.dataset.prompt));init();
